import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:go_router/go_router.dart';

class ShopScreen extends StatefulWidget {
  const ShopScreen({super.key});

  @override
  State<ShopScreen> createState() => _ShopScreenState();
}

class _ShopScreenState extends State<ShopScreen> {
  String _selectedCategory = 'All';
  String _sortBy = 'Popularity';
  bool _showSortMenu = false;
  int _cartCount = 0;
  final TextEditingController _searchController = TextEditingController();
  String _searchQuery = '';

  final List<Map<String, dynamic>> _allProducts = [
    {
      'id': 1,
      'name': 'तांबे का कलश',
      'description': 'Sacred तांबे का कलश (1 pcs) for Kalash Sthapana. Requirement: Required.',
      'price': 150.0,
      'category': 'Kalash Sthapana',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 pcs', 'Kalash Sthapana', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 2,
      'name': 'नारियल',
      'description': 'Sacred नारियल (2 pcs) for Kalash Sthapana. Requirement: Required.',
      'price': 187.0,
      'category': 'Kalash Sthapana',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['2 pcs', 'Kalash Sthapana', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 3,
      'name': 'आम के पत्ते',
      'description': 'Sacred आम के पत्ते (11 pcs) for Kalash Sthapana. Requirement: Required.',
      'price': 224.0,
      'category': 'Kalash Sthapana',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['11 pcs', 'Kalash Sthapana', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 4,
      'name': 'मौली / कलावा',
      'description': 'Sacred मौली / कलावा (1 roll) for Kalash Sthapana. Requirement: Required.',
      'price': 261.0,
      'category': 'Kalash Sthapana',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 roll', 'Kalash Sthapana', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 5,
      'name': 'लाल कपड़ा',
      'description': 'Sacred लाल कपड़ा (1 meter) for Kalash Sthapana. Requirement: Required.',
      'price': 298.0,
      'category': 'Kalash Sthapana',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 meter', 'Kalash Sthapana', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 6,
      'name': 'अक्षत (चावल)',
      'description': 'Sacred अक्षत (चावल) (1 kg) for Kalash Sthapana. Requirement: Required.',
      'price': 335.0,
      'category': 'Kalash Sthapana',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 kg', 'Kalash Sthapana', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 7,
      'name': 'रोली / कुमकुम',
      'description': 'Sacred रोली / कुमकुम (100 gm) for Kalash Sthapana. Requirement: Required.',
      'price': 372.0,
      'category': 'Kalash Sthapana',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['100 gm', 'Kalash Sthapana', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 8,
      'name': 'हल्दी',
      'description': 'Sacred हल्दी (100 gm) for Kalash Sthapana. Requirement: Required.',
      'price': 409.0,
      'category': 'Kalash Sthapana',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['100 gm', 'Kalash Sthapana', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 9,
      'name': 'सुपारी',
      'description': 'Sacred सुपारी (21 pcs) for Kalash Sthapana. Requirement: Required.',
      'price': 446.0,
      'category': 'Kalash Sthapana',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['21 pcs', 'Kalash Sthapana', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 10,
      'name': 'सिक्का',
      'description': 'Sacred सिक्का (11 pcs) for Kalash Sthapana. Requirement: Required.',
      'price': 483.0,
      'category': 'Kalash Sthapana',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['11 pcs', 'Kalash Sthapana', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 11,
      'name': 'गंगाजल',
      'description': 'Sacred गंगाजल (1 bottle) for Kalash Sthapana. Requirement: Required.',
      'price': 520.0,
      'category': 'Kalash Sthapana',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 bottle', 'Kalash Sthapana', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 12,
      'name': 'रोली',
      'description': 'Sacred रोली (100 gm) for मुख्य पूजा सामग्री. Requirement: Required.',
      'price': 557.0,
      'category': 'मुख्य पूजा सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['100 gm', 'मुख्य पूजा सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 13,
      'name': 'कुमकुम',
      'description': 'Sacred कुमकुम (100 gm) for मुख्य पूजा सामग्री. Requirement: Required.',
      'price': 594.0,
      'category': 'मुख्य पूजा सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['100 gm', 'मुख्य पूजा सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 14,
      'name': 'हल्दी पाउडर',
      'description': 'Sacred हल्दी पाउडर (100 gm) for मुख्य पूजा सामग्री. Requirement: Required.',
      'price': 181.0,
      'category': 'मुख्य पूजा सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['100 gm', 'मुख्य पूजा सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 15,
      'name': 'हल्दी गांठ',
      'description': 'Sacred हल्दी गांठ (100 gm) for मुख्य पूजा सामग्री. Requirement: Required.',
      'price': 218.0,
      'category': 'मुख्य पूजा सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['100 gm', 'मुख्य पूजा सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 16,
      'name': 'चंदन',
      'description': 'Sacred चंदन (50 gm) for मुख्य पूजा सामग्री. Requirement: Required.',
      'price': 255.0,
      'category': 'मुख्य पूजा सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['50 gm', 'मुख्य पूजा सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 17,
      'name': 'लाल चंदन',
      'description': 'Sacred लाल चंदन (50 gm) for मुख्य पूजा सामग्री. Requirement: Required.',
      'price': 292.0,
      'category': 'मुख्य पूजा सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['50 gm', 'मुख्य पूजा सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 18,
      'name': 'सफेद चंदन',
      'description': 'Sacred सफेद चंदन (50 gm) for मुख्य पूजा सामग्री. Requirement: Required.',
      'price': 329.0,
      'category': 'मुख्य पूजा सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['50 gm', 'मुख्य पूजा सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 19,
      'name': 'अक्षत',
      'description': 'Sacred अक्षत (2 kg) for मुख्य पूजा सामग्री. Requirement: Required.',
      'price': 366.0,
      'category': 'मुख्य पूजा सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['2 kg', 'मुख्य पूजा सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 20,
      'name': 'जौ',
      'description': 'Sacred जौ (1 kg) for मुख्य पूजा सामग्री. Requirement: Required.',
      'price': 403.0,
      'category': 'मुख्य पूजा सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 kg', 'मुख्य पूजा सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 21,
      'name': 'तिल सफेद',
      'description': 'Sacred तिल सफेद (250 gm) for मुख्य पूजा सामग्री. Requirement: Required.',
      'price': 440.0,
      'category': 'मुख्य पूजा सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['250 gm', 'मुख्य पूजा सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 22,
      'name': 'तिल काला',
      'description': 'Sacred तिल काला (250 gm) for मुख्य पूजा सामग्री. Requirement: Required.',
      'price': 477.0,
      'category': 'मुख्य पूजा सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['250 gm', 'मुख्य पूजा सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 23,
      'name': 'गेहूं',
      'description': 'Sacred गेहूं (1 kg) for मुख्य पूजा सामग्री. Requirement: Required.',
      'price': 514.0,
      'category': 'मुख्य पूजा सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 kg', 'मुख्य पूजा सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 24,
      'name': 'मूंग',
      'description': 'Sacred मूंग (500 gm) for मुख्य पूजा सामग्री. Requirement: Required.',
      'price': 551.0,
      'category': 'मुख्य पूजा सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['500 gm', 'मुख्य पूजा सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 25,
      'name': 'चना',
      'description': 'Sacred चना (500 gm) for मुख्य पूजा सामग्री. Requirement: Required.',
      'price': 588.0,
      'category': 'मुख्य पूजा सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['500 gm', 'मुख्य पूजा सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 26,
      'name': 'मसूर',
      'description': 'Sacred मसूर (500 gm) for मुख्य पूजा सामग्री. Requirement: Required.',
      'price': 175.0,
      'category': 'मुख्य पूजा सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['500 gm', 'मुख्य पूजा सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 27,
      'name': 'पंचरत्न',
      'description': 'Sacred पंचरत्न (1 packet) for मुख्य पूजा सामग्री. Requirement: Required.',
      'price': 212.0,
      'category': 'मुख्य पूजा सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 packet', 'मुख्य पूजा सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 28,
      'name': 'पंचमेवा',
      'description': 'Sacred पंचमेवा (500 gm) for मुख्य पूजा सामग्री. Requirement: Required.',
      'price': 249.0,
      'category': 'मुख्य पूजा सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['500 gm', 'मुख्य पूजा सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 29,
      'name': 'बताशा',
      'description': 'Sacred बताशा (500 gm) for मुख्य पूजा सामग्री. Requirement: Required.',
      'price': 286.0,
      'category': 'मुख्य पूजा सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['500 gm', 'मुख्य पूजा सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 30,
      'name': 'मिश्री',
      'description': 'Sacred मिश्री (500 gm) for मुख्य पूजा सामग्री. Requirement: Required.',
      'price': 323.0,
      'category': 'मुख्य पूजा सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['500 gm', 'मुख्य पूजा सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 31,
      'name': 'खील',
      'description': 'Sacred खील (500 gm) for मुख्य पूजा सामग्री. Requirement: Required.',
      'price': 360.0,
      'category': 'मुख्य पूजा सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['500 gm', 'मुख्य पूजा सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 32,
      'name': 'फूल माला',
      'description': 'Sacred फूल माला (5 pcs) for पुष्प एवं पत्ते. Requirement: Required.',
      'price': 397.0,
      'category': 'पुष्प एवं पत्ते',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['5 pcs', 'पुष्प एवं पत्ते', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 33,
      'name': 'गुलाब',
      'description': 'Sacred गुलाब (2 kg) for पुष्प एवं पत्ते. Requirement: Required.',
      'price': 434.0,
      'category': 'पुष्प एवं पत्ते',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['2 kg', 'पुष्प एवं पत्ते', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 34,
      'name': 'गेंदा फूल',
      'description': 'Sacred गेंदा फूल (2 kg) for पुष्प एवं पत्ते. Requirement: Required.',
      'price': 471.0,
      'category': 'पुष्प एवं पत्ते',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['2 kg', 'पुष्प एवं पत्ते', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 35,
      'name': 'कमल का फूल',
      'description': 'Sacred कमल का फूल (5 pcs) for पुष्प एवं पत्ते. Requirement: Required.',
      'price': 508.0,
      'category': 'पुष्प एवं पत्ते',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['5 pcs', 'पुष्प एवं पत्ते', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 36,
      'name': 'बेलपत्र',
      'description': 'Sacred बेलपत्र (108 leaves) for पुष्प एवं पत्ते. Requirement: Required.',
      'price': 545.0,
      'category': 'पुष्प एवं पत्ते',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['108 leaves', 'पुष्प एवं पत्ते', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 37,
      'name': 'दूर्वा',
      'description': 'Sacred दूर्वा (5 bundle) for पुष्प एवं पत्ते. Requirement: Required.',
      'price': 582.0,
      'category': 'पुष्प एवं पत्ते',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['5 bundle', 'पुष्प एवं पत्ते', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 38,
      'name': 'तुलसी पत्ता',
      'description': 'Sacred तुलसी पत्ता (1 bundle) for पुष्प एवं पत्ते. Requirement: Required.',
      'price': 169.0,
      'category': 'पुष्प एवं पत्ते',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 bundle', 'पुष्प एवं पत्ते', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 39,
      'name': 'पान के पत्ते',
      'description': 'Sacred पान के पत्ते (21 pcs) for पुष्प एवं पत्ते. Requirement: Required.',
      'price': 206.0,
      'category': 'पुष्प एवं पत्ते',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['21 pcs', 'पुष्प एवं पत्ते', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 40,
      'name': 'नारियल',
      'description': 'Sacred नारियल (11 pcs) for फल एवं प्रसाद. Requirement: Required.',
      'price': 243.0,
      'category': 'फल एवं प्रसाद',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['11 pcs', 'फल एवं प्रसाद', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 41,
      'name': 'केला',
      'description': 'Sacred केला (2 dozen) for फल एवं प्रसाद. Requirement: Required.',
      'price': 280.0,
      'category': 'फल एवं प्रसाद',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['2 dozen', 'फल एवं प्रसाद', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 42,
      'name': 'सेब',
      'description': 'Sacred सेब (2 kg) for फल एवं प्रसाद. Requirement: Required.',
      'price': 317.0,
      'category': 'फल एवं प्रसाद',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['2 kg', 'फल एवं प्रसाद', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 43,
      'name': 'संतरा',
      'description': 'Sacred संतरा (2 kg) for फल एवं प्रसाद. Requirement: Required.',
      'price': 354.0,
      'category': 'फल एवं प्रसाद',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['2 kg', 'फल एवं प्रसाद', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 44,
      'name': 'अनार',
      'description': 'Sacred अनार (1 kg) for फल एवं प्रसाद. Requirement: Required.',
      'price': 391.0,
      'category': 'फल एवं प्रसाद',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 kg', 'फल एवं प्रसाद', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 45,
      'name': 'अंगूर',
      'description': 'Sacred अंगूर (1 kg) for फल एवं प्रसाद. Requirement: Required.',
      'price': 428.0,
      'category': 'फल एवं प्रसाद',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 kg', 'फल एवं प्रसाद', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 46,
      'name': 'मिठाई',
      'description': 'Sacred मिठाई (2 kg) for फल एवं प्रसाद. Requirement: Required.',
      'price': 465.0,
      'category': 'फल एवं प्रसाद',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['2 kg', 'फल एवं प्रसाद', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 47,
      'name': 'लड्डू',
      'description': 'Sacred लड्डू (1 kg) for फल एवं प्रसाद. Requirement: Required.',
      'price': 502.0,
      'category': 'फल एवं प्रसाद',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 kg', 'फल एवं प्रसाद', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 48,
      'name': 'पेड़ा',
      'description': 'Sacred पेड़ा (1 kg) for फल एवं प्रसाद. Requirement: Required.',
      'price': 539.0,
      'category': 'फल एवं प्रसाद',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 kg', 'फल एवं प्रसाद', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 49,
      'name': 'पंजीरी',
      'description': 'Sacred पंजीरी (1 kg) for फल एवं प्रसाद. Requirement: Required.',
      'price': 576.0,
      'category': 'फल एवं प्रसाद',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 kg', 'फल एवं प्रसाद', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 50,
      'name': 'दूध',
      'description': 'Sacred दूध (2 litre) for पंचामृत. Requirement: Required.',
      'price': 163.0,
      'category': 'पंचामृत',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['2 litre', 'पंचामृत', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 51,
      'name': 'दही',
      'description': 'Sacred दही (1 kg) for पंचामृत. Requirement: Required.',
      'price': 200.0,
      'category': 'पंचामृत',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 kg', 'पंचामृत', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 52,
      'name': 'घी',
      'description': 'Sacred घी (500 gm) for पंचामृत. Requirement: Required.',
      'price': 237.0,
      'category': 'पंचामृत',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['500 gm', 'पंचामृत', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 53,
      'name': 'शहद',
      'description': 'Sacred शहद (250 gm) for पंचामृत. Requirement: Required.',
      'price': 274.0,
      'category': 'पंचामृत',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['250 gm', 'पंचामृत', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 54,
      'name': 'शक्कर / मिश्री',
      'description': 'Sacred शक्कर / मिश्री (500 gm) for पंचामृत. Requirement: Required.',
      'price': 311.0,
      'category': 'पंचामृत',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['500 gm', 'पंचामृत', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 55,
      'name': 'हवन कुंड',
      'description': 'Sacred हवन कुंड (1 pcs) for हवन सामग्री. Requirement: Required.',
      'price': 348.0,
      'category': 'हवन सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 pcs', 'हवन सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 56,
      'name': 'हवन सामग्री',
      'description': 'Sacred हवन सामग्री (2 kg) for हवन सामग्री. Requirement: Required.',
      'price': 385.0,
      'category': 'हवन सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['2 kg', 'हवन सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 57,
      'name': 'हवन समिधा',
      'description': 'Sacred हवन समिधा (5 bundle) for हवन सामग्री. Requirement: Required.',
      'price': 422.0,
      'category': 'हवन सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['5 bundle', 'हवन सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 58,
      'name': 'आम की लकड़ी',
      'description': 'Sacred आम की लकड़ी (5 kg) for हवन सामग्री. Requirement: Required.',
      'price': 459.0,
      'category': 'हवन सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['5 kg', 'हवन सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 59,
      'name': 'कपूर',
      'description': 'Sacred कपूर (100 gm) for हवन सामग्री. Requirement: Required.',
      'price': 496.0,
      'category': 'हवन सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['100 gm', 'हवन सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 60,
      'name': 'शुद्ध घी',
      'description': 'Sacred शुद्ध घी (1 kg) for हवन सामग्री. Requirement: Required.',
      'price': 533.0,
      'category': 'हवन सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 kg', 'हवन सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 61,
      'name': 'जौ',
      'description': 'Sacred जौ (500 gm) for हवन सामग्री. Requirement: Required.',
      'price': 570.0,
      'category': 'हवन सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['500 gm', 'हवन सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 62,
      'name': 'काला तिल',
      'description': 'Sacred काला तिल (250 gm) for हवन सामग्री. Requirement: Required.',
      'price': 157.0,
      'category': 'हवन सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['250 gm', 'हवन सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 63,
      'name': 'सफेद तिल',
      'description': 'Sacred सफेद तिल (250 gm) for हवन सामग्री. Requirement: Required.',
      'price': 194.0,
      'category': 'हवन सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['250 gm', 'हवन सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 64,
      'name': 'चावल',
      'description': 'Sacred चावल (500 gm) for हवन सामग्री. Requirement: Required.',
      'price': 231.0,
      'category': 'हवन सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['500 gm', 'हवन सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 65,
      'name': 'लौंग',
      'description': 'Sacred लौंग (50 gm) for हवन सामग्री. Requirement: Required.',
      'price': 268.0,
      'category': 'हवन सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['50 gm', 'हवन सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 66,
      'name': 'इलायची',
      'description': 'Sacred इलायची (50 gm) for हवन सामग्री. Requirement: Required.',
      'price': 305.0,
      'category': 'हवन सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['50 gm', 'हवन सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 67,
      'name': 'गुग्गुल',
      'description': 'Sacred गुग्गुल (100 gm) for हवन सामग्री. Requirement: Required.',
      'price': 342.0,
      'category': 'हवन सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['100 gm', 'हवन सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 68,
      'name': 'लोबान',
      'description': 'Sacred लोबान (100 gm) for हवन सामग्री. Requirement: Required.',
      'price': 379.0,
      'category': 'हवन सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['100 gm', 'हवन सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 69,
      'name': 'शक्कर',
      'description': 'Sacred शक्कर (500 gm) for हवन सामग्री. Requirement: Required.',
      'price': 416.0,
      'category': 'हवन सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['500 gm', 'हवन सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 70,
      'name': 'सूखा नारियल / गोला',
      'description': 'Sacred सूखा नारियल / गोला (5 pcs) for हवन सामग्री. Requirement: Required.',
      'price': 453.0,
      'category': 'हवन सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['5 pcs', 'हवन सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 71,
      'name': 'नवग्रह समिधा',
      'description': 'Sacred नवग्रह समिधा (1 set) for हवन सामग्री. Requirement: Required.',
      'price': 490.0,
      'category': 'हवन सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 set', 'हवन सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 72,
      'name': 'मिट्टी के दीपक',
      'description': 'Sacred मिट्टी के दीपक (51 pcs) for दीपक एवं आरती. Requirement: Required.',
      'price': 527.0,
      'category': 'दीपक एवं आरती',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['51 pcs', 'दीपक एवं आरती', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 73,
      'name': 'पीतल का दीपक',
      'description': 'Sacred पीतल का दीपक (2 pcs) for दीपक एवं आरती. Requirement: Required.',
      'price': 564.0,
      'category': 'दीपक एवं आरती',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['2 pcs', 'दीपक एवं आरती', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 74,
      'name': 'रुई बत्ती',
      'description': 'Sacred रुई बत्ती (1 packet) for दीपक एवं आरती. Requirement: Required.',
      'price': 151.0,
      'category': 'दीपक एवं आरती',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 packet', 'दीपक एवं आरती', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 75,
      'name': 'घी',
      'description': 'Sacred घी (500 gm) for दीपक एवं आरती. Requirement: Required.',
      'price': 188.0,
      'category': 'दीपक एवं आरती',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['500 gm', 'दीपक एवं आरती', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 76,
      'name': 'सरसों तेल',
      'description': 'Sacred सरसों तेल (500 ml) for दीपक एवं आरती. Requirement: Required.',
      'price': 225.0,
      'category': 'दीपक एवं आरती',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['500 ml', 'दीपक एवं आरती', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 77,
      'name': 'कपूर',
      'description': 'Sacred कपूर (100 gm) for दीपक एवं आरती. Requirement: Required.',
      'price': 262.0,
      'category': 'दीपक एवं आरती',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['100 gm', 'दीपक एवं आरती', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 78,
      'name': 'धूप',
      'description': 'Sacred धूप (1 packet) for दीपक एवं आरती. Requirement: Required.',
      'price': 299.0,
      'category': 'दीपक एवं आरती',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 packet', 'दीपक एवं आरती', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 79,
      'name': 'अगरबत्ती',
      'description': 'Sacred अगरबत्ती (2 packet) for दीपक एवं आरती. Requirement: Required.',
      'price': 336.0,
      'category': 'दीपक एवं आरती',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['2 packet', 'दीपक एवं आरती', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 80,
      'name': 'धूपदानी',
      'description': 'Sacred धूपदानी (1 pcs) for दीपक एवं आरती. Requirement: Required.',
      'price': 373.0,
      'category': 'दीपक एवं आरती',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 pcs', 'दीपक एवं आरती', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 81,
      'name': 'आरती थाली',
      'description': 'Sacred आरती थाली (1 pcs) for दीपक एवं आरती. Requirement: Required.',
      'price': 410.0,
      'category': 'दीपक एवं आरती',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 pcs', 'दीपक एवं आरती', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 82,
      'name': 'गणेश जी की मूर्ति / प्रतिमा',
      'description': 'Sacred गणेश जी की मूर्ति / प्रतिमा (1 pcs) for गणेश पूजा. Requirement: Required.',
      'price': 447.0,
      'category': 'गणेश पूजा',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 pcs', 'गणेश पूजा', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 83,
      'name': 'दूर्वा',
      'description': 'Sacred दूर्वा (21 bundle) for गणेश पूजा. Requirement: Required.',
      'price': 484.0,
      'category': 'गणेश पूजा',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['21 bundle', 'गणेश पूजा', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 84,
      'name': 'मोदक / लड्डू',
      'description': 'Sacred मोदक / लड्डू (21 pcs) for गणेश पूजा. Requirement: Required.',
      'price': 521.0,
      'category': 'गणेश पूजा',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['21 pcs', 'गणेश पूजा', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 85,
      'name': 'सिंदूर',
      'description': 'Sacred सिंदूर (50 gm) for गणेश पूजा. Requirement: Required.',
      'price': 558.0,
      'category': 'गणेश पूजा',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['50 gm', 'गणेश पूजा', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 86,
      'name': 'लाल फूल',
      'description': 'Sacred लाल फूल (21 pcs) for गणेश पूजा. Requirement: Required.',
      'price': 595.0,
      'category': 'गणेश पूजा',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['21 pcs', 'गणेश पूजा', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 87,
      'name': 'सुपारी',
      'description': 'Sacred सुपारी (5 pcs) for गणेश पूजा. Requirement: Required.',
      'price': 182.0,
      'category': 'गणेश पूजा',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['5 pcs', 'गणेश पूजा', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 88,
      'name': 'शिवलिंग',
      'description': 'Sacred शिवलिंग (1 pcs) for शिव पूजा. Requirement: Required.',
      'price': 219.0,
      'category': 'शिव पूजा',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 pcs', 'शिव पूजा', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 89,
      'name': 'बेलपत्र',
      'description': 'Sacred बेलपत्र (108 leaves) for शिव पूजा. Requirement: Required.',
      'price': 256.0,
      'category': 'शिव पूजा',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['108 leaves', 'शिव पूजा', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 90,
      'name': 'भस्म',
      'description': 'Sacred भस्म (50 gm) for शिव पूजा. Requirement: Required.',
      'price': 293.0,
      'category': 'शिव पूजा',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['50 gm', 'शिव पूजा', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 91,
      'name': 'धतूरा',
      'description': 'Sacred धतूरा (5 pcs) for शिव पूजा. Requirement: Required.',
      'price': 330.0,
      'category': 'शिव पूजा',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['5 pcs', 'शिव पूजा', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 92,
      'name': 'आक के फूल',
      'description': 'Sacred आक के फूल (21 pcs) for शिव पूजा. Requirement: Required.',
      'price': 367.0,
      'category': 'शिव पूजा',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['21 pcs', 'शिव पूजा', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 93,
      'name': 'दूध',
      'description': 'Sacred दूध (2 litre) for शिव पूजा. Requirement: Required.',
      'price': 404.0,
      'category': 'शिव पूजा',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['2 litre', 'शिव पूजा', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 94,
      'name': 'गंगाजल',
      'description': 'Sacred गंगाजल (1 bottle) for शिव पूजा. Requirement: Required.',
      'price': 441.0,
      'category': 'शिव पूजा',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 bottle', 'शिव पूजा', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 95,
      'name': 'लाल चुनरी',
      'description': 'Sacred लाल चुनरी (2 pcs) for देवी पूजा. Requirement: Required.',
      'price': 478.0,
      'category': 'देवी पूजा',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['2 pcs', 'देवी पूजा', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 96,
      'name': 'लाल कपड़ा',
      'description': 'Sacred लाल कपड़ा (2 meter) for देवी पूजा. Requirement: Required.',
      'price': 515.0,
      'category': 'देवी पूजा',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['2 meter', 'देवी पूजा', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 97,
      'name': 'लाल फूल',
      'description': 'Sacred लाल फूल (2 kg) for देवी पूजा. Requirement: Required.',
      'price': 552.0,
      'category': 'देवी पूजा',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['2 kg', 'देवी पूजा', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 98,
      'name': 'सिंदूर',
      'description': 'Sacred सिंदूर (100 gm) for देवी पूजा. Requirement: Required.',
      'price': 589.0,
      'category': 'देवी पूजा',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['100 gm', 'देवी पूजा', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 99,
      'name': 'कुमकुम',
      'description': 'Sacred कुमकुम (100 gm) for देवी पूजा. Requirement: Required.',
      'price': 176.0,
      'category': 'देवी पूजा',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['100 gm', 'देवी पूजा', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 100,
      'name': 'श्रृंगार सामग्री',
      'description': 'Sacred श्रृंगार सामग्री (1 set) for देवी पूजा. Requirement: Required.',
      'price': 213.0,
      'category': 'देवी पूजा',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 set', 'देवी पूजा', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 101,
      'name': 'लाल चूड़ी',
      'description': 'Sacred लाल चूड़ी (1 set) for देवी पूजा. Requirement: Required.',
      'price': 250.0,
      'category': 'देवी पूजा',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 set', 'देवी पूजा', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 102,
      'name': 'बिंदी',
      'description': 'Sacred बिंदी (1 packet) for देवी पूजा. Requirement: Required.',
      'price': 287.0,
      'category': 'देवी पूजा',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 packet', 'देवी पूजा', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 103,
      'name': 'मेहंदी',
      'description': 'Sacred मेहंदी (100 gm) for देवी पूजा. Requirement: Required.',
      'price': 324.0,
      'category': 'देवी पूजा',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['100 gm', 'देवी पूजा', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 104,
      'name': 'इत्र',
      'description': 'Sacred इत्र (1 bottle) for देवी पूजा. Requirement: Required.',
      'price': 361.0,
      'category': 'देवी पूजा',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 bottle', 'देवी पूजा', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 105,
      'name': 'तुलसी दल',
      'description': 'Sacred तुलसी दल (1 bundle) for विष्णु / सत्यनारायण. Requirement: Required.',
      'price': 398.0,
      'category': 'विष्णु / सत्यनारायण',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 bundle', 'विष्णु / सत्यनारायण', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 106,
      'name': 'पीला कपड़ा',
      'description': 'Sacred पीला कपड़ा (2 meter) for विष्णु / सत्यनारायण. Requirement: Required.',
      'price': 435.0,
      'category': 'विष्णु / सत्यनारायण',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['2 meter', 'विष्णु / सत्यनारायण', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 107,
      'name': 'पीले फूल',
      'description': 'Sacred पीले फूल (1 kg) for विष्णु / सत्यनारायण. Requirement: Required.',
      'price': 472.0,
      'category': 'विष्णु / सत्यनारायण',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 kg', 'विष्णु / सत्यनारायण', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 108,
      'name': 'केले',
      'description': 'Sacred केले (2 dozen) for विष्णु / सत्यनारायण. Requirement: Required.',
      'price': 509.0,
      'category': 'विष्णु / सत्यनारायण',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['2 dozen', 'विष्णु / सत्यनारायण', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 109,
      'name': 'पंचमेवा',
      'description': 'Sacred पंचमेवा (500 gm) for विष्णु / सत्यनारायण. Requirement: Required.',
      'price': 546.0,
      'category': 'विष्णु / सत्यनारायण',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['500 gm', 'विष्णु / सत्यनारायण', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 110,
      'name': 'गेहूं',
      'description': 'Sacred गेहूं (500 gm) for नवग्रह पूजा. Requirement: Required.',
      'price': 583.0,
      'category': 'नवग्रह पूजा',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['500 gm', 'नवग्रह पूजा', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 111,
      'name': 'चावल',
      'description': 'Sacred चावल (500 gm) for नवग्रह पूजा. Requirement: Required.',
      'price': 170.0,
      'category': 'नवग्रह पूजा',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['500 gm', 'नवग्रह पूजा', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 112,
      'name': 'मूंग',
      'description': 'Sacred मूंग (500 gm) for नवग्रह पूजा. Requirement: Required.',
      'price': 207.0,
      'category': 'नवग्रह पूजा',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['500 gm', 'नवग्रह पूजा', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 113,
      'name': 'उड़द',
      'description': 'Sacred उड़द (500 gm) for नवग्रह पूजा. Requirement: Required.',
      'price': 244.0,
      'category': 'नवग्रह पूजा',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['500 gm', 'नवग्रह पूजा', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 114,
      'name': 'मसूर',
      'description': 'Sacred मसूर (500 gm) for नवग्रह पूजा. Requirement: Required.',
      'price': 281.0,
      'category': 'नवग्रह पूजा',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['500 gm', 'नवग्रह पूजा', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 115,
      'name': 'चना',
      'description': 'Sacred चना (500 gm) for नवग्रह पूजा. Requirement: Required.',
      'price': 318.0,
      'category': 'नवग्रह पूजा',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['500 gm', 'नवग्रह पूजा', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 116,
      'name': 'जौ',
      'description': 'Sacred जौ (500 gm) for नवग्रह पूजा. Requirement: Required.',
      'price': 355.0,
      'category': 'नवग्रह पूजा',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['500 gm', 'नवग्रह पूजा', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 117,
      'name': 'काला तिल',
      'description': 'Sacred काला तिल (500 gm) for नवग्रह पूजा. Requirement: Required.',
      'price': 392.0,
      'category': 'नवग्रह पूजा',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['500 gm', 'नवग्रह पूजा', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 118,
      'name': 'सफेद तिल',
      'description': 'Sacred सफेद तिल (500 gm) for नवग्रह पूजा. Requirement: Required.',
      'price': 429.0,
      'category': 'नवग्रह पूजा',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['500 gm', 'नवग्रह पूजा', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 119,
      'name': 'नवग्रह वस्त्र',
      'description': 'Sacred नवग्रह वस्त्र (1 set) for नवग्रह पूजा. Requirement: Required.',
      'price': 466.0,
      'category': 'नवग्रह पूजा',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 set', 'नवग्रह पूजा', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 120,
      'name': 'लाल कपड़ा',
      'description': 'Sacred लाल कपड़ा (5 meter) for वस्त्र एवं अन्य. Requirement: Required.',
      'price': 503.0,
      'category': 'वस्त्र एवं अन्य',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['5 meter', 'वस्त्र एवं अन्य', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 121,
      'name': 'पीला कपड़ा',
      'description': 'Sacred पीला कपड़ा (5 meter) for वस्त्र एवं अन्य. Requirement: Required.',
      'price': 540.0,
      'category': 'वस्त्र एवं अन्य',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['5 meter', 'वस्त्र एवं अन्य', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 122,
      'name': 'सफेद कपड़ा',
      'description': 'Sacred सफेद कपड़ा (5 meter) for वस्त्र एवं अन्य. Requirement: Required.',
      'price': 577.0,
      'category': 'वस्त्र एवं अन्य',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['5 meter', 'वस्त्र एवं अन्य', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 123,
      'name': 'मौली / कलावा',
      'description': 'Sacred मौली / कलावा (2 roll) for वस्त्र एवं अन्य. Requirement: Required.',
      'price': 164.0,
      'category': 'वस्त्र एवं अन्य',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['2 roll', 'वस्त्र एवं अन्य', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 124,
      'name': 'जनेऊ',
      'description': 'Sacred जनेऊ (21 pcs) for वस्त्र एवं अन्य. Requirement: Required.',
      'price': 201.0,
      'category': 'वस्त्र एवं अन्य',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['21 pcs', 'वस्त्र एवं अन्य', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 125,
      'name': 'आसन',
      'description': 'Sacred आसन (5 pcs) for वस्त्र एवं अन्य. Requirement: Required.',
      'price': 238.0,
      'category': 'वस्त्र एवं अन्य',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['5 pcs', 'वस्त्र एवं अन्य', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 126,
      'name': 'पूजा चौकी',
      'description': 'Sacred पूजा चौकी (2 pcs) for वस्त्र एवं अन्य. Requirement: Required.',
      'price': 275.0,
      'category': 'वस्त्र एवं अन्य',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['2 pcs', 'वस्त्र एवं अन्य', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 127,
      'name': 'थाली',
      'description': 'Sacred थाली (5 pcs) for वस्त्र एवं अन्य. Requirement: Required.',
      'price': 312.0,
      'category': 'वस्त्र एवं अन्य',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['5 pcs', 'वस्त्र एवं अन्य', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 128,
      'name': 'कटोरी',
      'description': 'Sacred कटोरी (11 pcs) for वस्त्र एवं अन्य. Requirement: Required.',
      'price': 349.0,
      'category': 'वस्त्र एवं अन्य',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['11 pcs', 'वस्त्र एवं अन्य', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 129,
      'name': 'लोटा',
      'description': 'Sacred लोटा (2 pcs) for वस्त्र एवं अन्य. Requirement: Required.',
      'price': 386.0,
      'category': 'वस्त्र एवं अन्य',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['2 pcs', 'वस्त्र एवं अन्य', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 130,
      'name': 'चम्मच',
      'description': 'Sacred चम्मच (5 pcs) for वस्त्र एवं अन्य. Requirement: Required.',
      'price': 423.0,
      'category': 'वस्त्र एवं अन्य',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['5 pcs', 'वस्त्र एवं अन्य', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 131,
      'name': 'घंटी',
      'description': 'Sacred घंटी (1 pcs) for वस्त्र एवं अन्य. Requirement: Required.',
      'price': 460.0,
      'category': 'वस्त्र एवं अन्य',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 pcs', 'वस्त्र एवं अन्य', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 132,
      'name': 'शंख',
      'description': 'Sacred शंख (1 pcs) for वस्त्र एवं अन्य. Requirement: Required.',
      'price': 497.0,
      'category': 'वस्त्र एवं अन्य',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 pcs', 'वस्त्र एवं अन्य', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 133,
      'name': 'पंचपात्र',
      'description': 'Sacred पंचपात्र (1 set) for वस्त्र एवं अन्य. Requirement: Required.',
      'price': 534.0,
      'category': 'वस्त्र एवं अन्य',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 set', 'वस्त्र एवं अन्य', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 134,
      'name': 'नवग्रह यंत्र',
      'description': 'Sacred नवग्रह यंत्र (1 pcs) for विशेष सामग्री. Requirement: Required.',
      'price': 571.0,
      'category': 'विशेष सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 pcs', 'विशेष सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 135,
      'name': 'गणेश यंत्र',
      'description': 'Sacred गणेश यंत्र (1 pcs) for विशेष सामग्री. Requirement: Required.',
      'price': 158.0,
      'category': 'विशेष सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 pcs', 'विशेष सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 136,
      'name': 'लक्ष्मी यंत्र',
      'description': 'Sacred लक्ष्मी यंत्र (1 pcs) for विशेष सामग्री. Requirement: Required.',
      'price': 195.0,
      'category': 'विशेष सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 pcs', 'विशेष सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 137,
      'name': 'कुबेर यंत्र',
      'description': 'Sacred कुबेर यंत्र (1 pcs) for विशेष सामग्री. Requirement: Required.',
      'price': 232.0,
      'category': 'विशेष सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 pcs', 'विशेष सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 138,
      'name': 'रुद्राक्ष',
      'description': 'Sacred रुद्राक्ष (1 set) for विशेष सामग्री. Requirement: Required.',
      'price': 269.0,
      'category': 'विशेष सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 set', 'विशेष सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 139,
      'name': 'शालिग्राम',
      'description': 'Sacred शालिग्राम (1 pcs) for विशेष सामग्री. Requirement: Required.',
      'price': 306.0,
      'category': 'विशेष सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 pcs', 'विशेष सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 140,
      'name': 'गोमती चक्र',
      'description': 'Sacred गोमती चक्र (11 pcs) for विशेष सामग्री. Requirement: Required.',
      'price': 343.0,
      'category': 'विशेष सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['11 pcs', 'विशेष सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 141,
      'name': 'कौड़ी',
      'description': 'Sacred कौड़ी (21 pcs) for विशेष सामग्री. Requirement: Required.',
      'price': 380.0,
      'category': 'विशेष सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['21 pcs', 'विशेष सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 142,
      'name': 'अष्टगंध',
      'description': 'Sacred अष्टगंध (50 gm) for विशेष सामग्री. Requirement: Required.',
      'price': 417.0,
      'category': 'विशेष सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['50 gm', 'विशेष सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 143,
      'name': 'केसर',
      'description': 'Sacred केसर (5 gm) for विशेष सामग्री. Requirement: Required.',
      'price': 454.0,
      'category': 'विशेष सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['5 gm', 'विशेष सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 144,
      'name': 'जायफल',
      'description': 'Sacred जायफल (11 pcs) for विशेष सामग्री. Requirement: Required.',
      'price': 491.0,
      'category': 'विशेष सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['11 pcs', 'विशेष सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 145,
      'name': 'जावित्री',
      'description': 'Sacred जावित्री (25 gm) for विशेष सामग्री. Requirement: Required.',
      'price': 528.0,
      'category': 'विशेष सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['25 gm', 'विशेष सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 146,
      'name': 'दालचीनी',
      'description': 'Sacred दालचीनी (50 gm) for विशेष सामग्री. Requirement: Required.',
      'price': 565.0,
      'category': 'विशेष सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['50 gm', 'विशेष सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 147,
      'name': 'गोमती चक्र',
      'description': 'Sacred गोमती चक्र (11 pcs) for विशेष सामग्री. Requirement: Required.',
      'price': 152.0,
      'category': 'विशेष सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['11 pcs', 'विशेष सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 148,
      'name': 'कौड़ी',
      'description': 'Sacred कौड़ी (21 pcs) for विशेष सामग्री. Requirement: Required.',
      'price': 189.0,
      'category': 'विशेष सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['21 pcs', 'विशेष सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 149,
      'name': 'शालिग्राम',
      'description': 'Sacred शालिग्राम (1 pcs) for विशेष सामग्री. Requirement: Required.',
      'price': 226.0,
      'category': 'विशेष सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 pcs', 'विशेष सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 150,
      'name': 'रुद्राक्ष',
      'description': 'Sacred रुद्राक्ष (1 set) for विशेष सामग्री. Requirement: Required.',
      'price': 263.0,
      'category': 'विशेष सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 set', 'विशेष सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 151,
      'name': 'पारद शिवलिंग',
      'description': 'Sacred पारद शिवलिंग (1 pcs) for विशेष सामग्री. Requirement: Required.',
      'price': 300.0,
      'category': 'विशेष सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 pcs', 'विशेष सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 152,
      'name': 'स्फटिक शिवलिंग',
      'description': 'Sacred स्फटिक शिवलिंग (1 pcs) for विशेष सामग्री. Requirement: Required.',
      'price': 337.0,
      'category': 'विशेष सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 pcs', 'विशेष सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 153,
      'name': 'नवग्रह यंत्र',
      'description': 'Sacred नवग्रह यंत्र (1 set) for विशेष सामग्री. Requirement: Required.',
      'price': 374.0,
      'category': 'विशेष सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 set', 'विशेष सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 154,
      'name': 'श्री यंत्र',
      'description': 'Sacred श्री यंत्र (1 pcs) for विशेष सामग्री. Requirement: Required.',
      'price': 411.0,
      'category': 'विशेष सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 pcs', 'विशेष सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 155,
      'name': 'कुबेर यंत्र',
      'description': 'Sacred कुबेर यंत्र (1 pcs) for विशेष सामग्री. Requirement: Required.',
      'price': 448.0,
      'category': 'विशेष सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 pcs', 'विशेष सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
    {
      'id': 156,
      'name': 'वास्तु यंत्र',
      'description': 'Sacred वास्तु यंत्र (1 pcs) for विशेष सामग्री. Requirement: Required.',
      'price': 485.0,
      'category': 'विशेष सामग्री',
      'badge': 'ESSENTIAL',
      'badgeColor': 4294020118,
      'samagri': ['1 pcs', 'विशेष सामग्री', 'Required'],
      'imagePath': 'assets/images/hawan_samagri.jpg',
    },
  ];

  List<Map<String, dynamic>> get _filteredProducts {
    List<Map<String, dynamic>> list = _allProducts;

    if (_selectedCategory != 'All') {
      list = list.where((p) => p['category'] == _selectedCategory).toList();
    }

    if (_searchQuery.isNotEmpty) {
      list = list
          .where(
            (p) =>
                (p['name'] as String).toLowerCase().contains(
                  _searchQuery.toLowerCase(),
                ) ||
                (p['description'] as String).toLowerCase().contains(
                  _searchQuery.toLowerCase(),
                ),
          )
          .toList();
    }

    if (_sortBy == 'Popularity') {
      list =
          list.where((p) => (p['badge'] as String) == 'ESSENTIAL').toList() +
          list.where((p) => (p['badge'] as String) != 'ESSENTIAL').toList();
    } else {
      list = [
        ...list,
      ]..sort((a, b) => (a['price'] as double).compareTo(b['price'] as double));
    }

    return list;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFFFF8EE),
      body: SafeArea(
        child: Stack(
          children: [
            Column(
              children: [
                Expanded(
                  child: SingleChildScrollView(
                    padding: const EdgeInsets.symmetric(
                      horizontal: 20,
                      vertical: 16,
                    ),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        _buildTopBar(),
                        const SizedBox(height: 20),
                        _buildSearchBar(),
                        const SizedBox(height: 18),
                        _buildOccasionRow(),
                        const SizedBox(height: 14),
                        _buildSortRow(),
                        const SizedBox(height: 16),
                        ..._buildProductCards(),
                        const SizedBox(height: 20),
                      ],
                    ),
                  ),
                ),
                _buildNavBar(context),
              ],
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildTopBar() {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Row(
          children: [
            Container(
              width: 42,
              height: 42,
              decoration: const BoxDecoration(
                color: Color(0xFFF18C16),
                shape: BoxShape.circle,
              ),
              child: const Icon(
                Icons.shopping_bag,
                color: Colors.white,
                size: 22,
              ),
            ),
            const SizedBox(width: 10),
            Text(
              'Pooja Store',
              style: GoogleFonts.lato(
                fontSize: 22,
                fontWeight: FontWeight.bold,
                color: const Color(0xFF3D2200),
              ),
            ),
          ],
        ),
        Stack(
          children: [
            IconButton(
              icon: const Icon(
                Icons.shopping_cart_outlined,
                size: 26,
                color: Color(0xFF3D2200),
              ),
              onPressed: () {},
            ),
            if (_cartCount > 0)
              Positioned(
                right: 6,
                top: 6,
                child: Container(
                  padding: const EdgeInsets.all(4),
                  decoration: const BoxDecoration(
                    color: Color(0xFFF18C16),
                    shape: BoxShape.circle,
                  ),
                  child: Text(
                    '$_cartCount',
                    style: GoogleFonts.lato(
                      color: Colors.white,
                      fontSize: 10,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
              ),
          ],
        ),
      ],
    );
  }

  Widget _buildSearchBar() {
    return Container(
      decoration: BoxDecoration(
        color: const Color(0xFFFAF0DC),
        borderRadius: BorderRadius.circular(28),
      ),
      padding: const EdgeInsets.symmetric(horizontal: 16),
      child: TextField(
        controller: _searchController,
        onChanged: (val) => setState(() => _searchQuery = val),
        decoration: InputDecoration(
          hintText: 'Search 156+ sacred items & samagri...',
          hintStyle: GoogleFonts.lato(fontSize: 14, color: Colors.grey),
          prefixIcon: const Icon(
            Icons.search,
            color: Color(0xFFE8920A),
            size: 22,
          ),
          filled: false,
          contentPadding: const EdgeInsets.symmetric(
            vertical: 14,
            horizontal: 4,
          ),
          border: InputBorder.none,
          enabledBorder: InputBorder.none,
          focusedBorder: InputBorder.none,
        ),
      ),
    );
  }

  Widget _buildOccasionRow() {
    final categories = [
      'All',
      'Kalash Sthapana',
      'मुख्य पूजा सामग्री',
      'पुष्प एवं पत्ते',
      'फल एवं प्रसाद',
      'पंचामृत',
      'हवन सामग्री',
      'दीपक एवं आरती',
      'गणेश पूजा',
      'शिव पूजा',
      'देवी पूजा',
      'विष्णु / सत्यनारायण',
      'नवग्रह पूजा',
      'वस्त्र एवं अन्य',
      'विशेष सामग्री',
    ];
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          'CATEGORY:',
          style: GoogleFonts.lato(
            fontWeight: FontWeight.bold,
            fontSize: 12,
            letterSpacing: 1.0,
            color: const Color(0xFF8A7060),
          ),
        ),
        const SizedBox(height: 10),
        SingleChildScrollView(
          scrollDirection: Axis.horizontal,
          child: Row(
            children: categories.map((cat) {
              final isActive = _selectedCategory == cat;
              return GestureDetector(
                onTap: () => setState(() => _selectedCategory = cat),
                child: Container(
                  margin: const EdgeInsets.only(right: 10),
                  padding: const EdgeInsets.symmetric(
                    horizontal: 18,
                    vertical: 8,
                  ),
                  decoration: BoxDecoration(
                    color: isActive ? const Color(0xFFF18C16) : Colors.white,
                    borderRadius: BorderRadius.circular(20),
                    border: Border.all(
                      color: isActive
                          ? const Color(0xFFF18C16)
                          : const Color(0xFFE8D5A3),
                      width: 1,
                    ),
                    boxShadow: isActive
                        ? [
                            BoxShadow(
                              color: const Color(
                                0xFFF18C16,
                              ).withValues(alpha: 0.3),
                              blurRadius: 6,
                              offset: const Offset(0, 2),
                            ),
                          ]
                        : null,
                  ),
                  child: Text(
                    cat,
                    style: GoogleFonts.lato(
                      fontWeight: FontWeight.bold,
                      fontSize: 13,
                      color: isActive ? Colors.white : const Color(0xFF3D2200),
                    ),
                  ),
                ),
              );
            }).toList(),
          ),
        ),
      ],
    );
  }

  Widget _buildSortRow() {
    return Row(
      children: [
        Text(
          'Sort by: ',
          style: GoogleFonts.lato(fontSize: 14, color: const Color(0xFF8A7060)),
        ),
        GestureDetector(
          onTap: () => setState(() => _showSortMenu = !_showSortMenu),
          child: Row(
            children: [
              Text(
                _sortBy,
                style: GoogleFonts.lato(
                  fontWeight: FontWeight.bold,
                  fontSize: 14,
                  color: const Color(0xFFE8920A),
                ),
              ),
              const Icon(
                Icons.arrow_drop_down,
                color: Color(0xFFE8920A),
                size: 20,
              ),
            ],
          ),
        ),
        if (_showSortMenu)
          Container(
            margin: const EdgeInsets.only(left: 8),
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(10),
              boxShadow: [
                BoxShadow(
                  color: Colors.black.withValues(alpha: 0.1),
                  blurRadius: 8,
                  offset: const Offset(0, 2),
                ),
              ],
            ),
            child: Column(
              children: ['Popularity', 'Lowest Price'].map((opt) {
                return GestureDetector(
                  onTap: () => setState(() {
                    _sortBy = opt;
                    _showSortMenu = false;
                  }),
                  child: Padding(
                    padding: const EdgeInsets.symmetric(
                      horizontal: 16,
                      vertical: 10,
                    ),
                    child: Text(
                      opt,
                      style: GoogleFonts.lato(
                        fontSize: 13,
                        fontWeight: FontWeight.w600,
                        color: const Color(0xFF3D2200),
                      ),
                    ),
                  ),
                );
              }).toList(),
            ),
          ),
      ],
    );
  }

  List<Widget> _buildProductCards() {
    final products = _filteredProducts;
    if (products.isEmpty) {
      return [
        Center(
          child: Padding(
            padding: const EdgeInsets.symmetric(vertical: 48),
            child: Column(
              children: [
                const Icon(
                  Icons.search_off,
                  color: Color(0xFFE8D5A3),
                  size: 64,
                ),
                const SizedBox(height: 12),
                Text(
                  'No Items Found',
                  style: GoogleFonts.lato(
                    fontWeight: FontWeight.bold,
                    fontSize: 18,
                    color: const Color(0xFF3D2200),
                  ),
                ),
                Text(
                  'Try adjusting your category or search filter.',
                  style: GoogleFonts.lato(
                    fontSize: 13,
                    color: const Color(0xFF8A7060),
                  ),
                ),
              ],
            ),
          ),
        ),
      ];
    }

    return products
        .map(
          (p) => Padding(
            padding: const EdgeInsets.only(bottom: 16),
            child: _ProductCard(
              product: p,
              onAddToCart: () {
                setState(() => _cartCount++);
                ScaffoldMessenger.of(context).showSnackBar(
                  SnackBar(
                    content: Text(
                      '${p['name']} added to cart!',
                      style: GoogleFonts.lato(color: Colors.white),
                    ),
                    backgroundColor: const Color(0xFFF18C16),
                    duration: const Duration(seconds: 2),
                    behavior: SnackBarBehavior.floating,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                );
              },
            ),
          ),
        )
        .toList();
  }

  Widget _buildNavBar(BuildContext context) {
    return Container(
      color: Colors.transparent,
      padding: const EdgeInsets.only(bottom: 16, top: 8, left: 16, right: 16),
      child: Container(
        height: 64,
        decoration: BoxDecoration(
          color: const Color(0xFF3D2200),
          borderRadius: BorderRadius.circular(40),
          boxShadow: [
            BoxShadow(
              color: Colors.black.withValues(alpha: 0.25),
              blurRadius: 16,
              offset: const Offset(0, 6),
            ),
          ],
        ),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.spaceAround,
          children: [
            _buildNavItem(0, Icons.home_outlined, Icons.home, 'Home', () => context.go('/home')),
            _buildNavItem(1, Icons.menu_book_outlined, Icons.menu_book, 'Book', () => context.go('/book')),
            _buildNavItem(2, Icons.calendar_month_outlined, Icons.calendar_month, 'Panchang', () => context.go('/panchang')),
            _buildNavItem(3, Icons.shopping_bag_outlined, Icons.shopping_bag, 'Shop', () {}),
            _buildNavItem(4, Icons.person_outline, Icons.person, 'Profile', () => context.go('/profile')),
          ],
        ),
      ),
    );
  }

  Widget _buildNavItem(int index, IconData icon, IconData activeIcon, String label, VoidCallback onTap) {
    final bool isSelected = index == 3;
    return GestureDetector(
      onTap: onTap,
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(
            isSelected ? activeIcon : icon,
            color: isSelected ? const Color(0xFFF18C16) : Colors.grey.shade400,
            size: 24,
          ),
          const SizedBox(height: 2),
          Text(
            label,
            style: GoogleFonts.lato(
              fontSize: 10,
              fontWeight: isSelected ? FontWeight.bold : FontWeight.normal,
              color: isSelected ? const Color(0xFFF18C16) : Colors.grey.shade400,
            ),
          ),
        ],
      ),
    );
  }
}

class _ProductCard extends StatelessWidget {
  final Map<String, dynamic> product;
  final VoidCallback onAddToCart;

  const _ProductCard({
    required this.product,
    required this.onAddToCart,
  });

  String _getProductImageUrl(Map<String, dynamic> product) {
    if (product['imageUrl'] != null && (product['imageUrl'] as String).isNotEmpty) {
      return product['imageUrl'];
    }
    final cat = (product['category'] as String? ?? '');
    final name = (product['name'] as String? ?? '');
    
    if (cat.contains('Kalash') || name.contains('कलश')) {
      return 'https://images.unsplash.com/photo-1608306448197-e83633f1261c?w=400&q=80';
    } else if (name.contains('नारियल') || name.contains('अक्षत') || name.contains('चावल')) {
      return 'https://images.unsplash.com/photo-1617981408346-39acb6da1b64?w=400&q=80';
    } else if (name.contains('फूल') || name.contains('पत्ते') || cat.contains('पुष्प')) {
      return 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=400&q=80';
    } else if (name.contains('हल्दी') || name.contains('कुमकुम') || name.contains('रोली')) {
      return 'https://images.unsplash.com/photo-1596704017254-9b121068fb31?w=400&q=80';
    } else if (cat.contains('हवन') || name.contains('हवन')) {
      return 'https://images.unsplash.com/photo-1605152276897-4f618f831968?w=400&q=80';
    } else if (cat.contains('दीपक') || name.contains('दीपक') || name.contains('आरती')) {
      return 'https://images.unsplash.com/photo-1609102434313-f938d87a718b?w=400&q=80';
    }
    return 'https://images.unsplash.com/photo-1596704017254-9b121068fb31?w=400&q=80';
  }

  @override
  Widget build(BuildContext context) {
    final List<String> samagri = (product['samagri'] as List? ?? []).cast<String>();

    return Container(
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(18),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.06),
            blurRadius: 10,
            offset: const Offset(0, 3),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(14),
                child: Image.network(
                  _getProductImageUrl(product),
                  width: 85,
                  height: 85,
                  fit: BoxFit.cover,
                  errorBuilder: (context, error, stackTrace) => Container(
                    width: 85,
                    height: 85,
                    decoration: const BoxDecoration(
                      color: Color(0xFFFFF3E0),
                      borderRadius: BorderRadius.all(Radius.circular(14)),
                    ),
                    child: const Center(
                      child: Icon(
                        Icons.inventory_2_outlined,
                        color: Color(0xFFF18C16),
                        size: 36,
                      ),
                    ),
                  ),
                ),
              ),
              const SizedBox(width: 14),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Expanded(
                          child: Text(
                            product['name'],
                            style: GoogleFonts.lato(
                              fontWeight: FontWeight.bold,
                              fontSize: 16,
                              color: const Color(0xFF3D2200),
                            ),
                          ),
                        ),
                        if ((product['badge'] as String).isNotEmpty)
                          Container(
                            padding: const EdgeInsets.symmetric(
                              horizontal: 8,
                              vertical: 3,
                            ),
                            decoration: BoxDecoration(
                              color: Color(product['badgeColor'] as int),
                              borderRadius: BorderRadius.circular(12),
                            ),
                            child: Text(
                              product['badge'],
                              style: GoogleFonts.lato(
                                color: Colors.white,
                                fontSize: 9,
                                fontWeight: FontWeight.bold,
                              ),
                            ),
                          ),
                      ],
                    ),
                    const SizedBox(height: 4),
                    Text(
                      product['description'],
                      style: GoogleFonts.lato(
                        fontSize: 12,
                        color: const Color(0xFF8A7060),
                      ),
                      maxLines: 2,
                      overflow: TextOverflow.ellipsis,
                    ),
                    const SizedBox(height: 8),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Text(
                          '₹${(product['price'] as double).toInt()}',
                          style: GoogleFonts.lato(
                            fontWeight: FontWeight.bold,
                            fontSize: 18,
                            color: const Color(0xFFF18C16),
                          ),
                        ),
                        Container(
                          decoration: BoxDecoration(
                            gradient: const LinearGradient(
                              colors: [Color(0xFFF18C16), Color(0xFFE65100)],
                            ),
                            borderRadius: BorderRadius.circular(12),
                            boxShadow: [
                              BoxShadow(
                                color: const Color(0xFFF18C16).withValues(alpha: 0.3),
                                blurRadius: 4,
                                offset: const Offset(0, 2),
                              ),
                            ],
                          ),
                          child: ElevatedButton(
                            onPressed: onAddToCart,
                            style: ElevatedButton.styleFrom(
                              backgroundColor: Colors.transparent,
                              shadowColor: Colors.transparent,
                              foregroundColor: Colors.white,
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(12),
                              ),
                              padding: const EdgeInsets.symmetric(
                                horizontal: 14,
                                vertical: 8,
                              ),
                              elevation: 0,
                            ),
                            child: Text(
                              'Add to Cart',
                              style: GoogleFonts.lato(
                                fontSize: 12,
                                fontWeight: FontWeight.bold,
                              ),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            ],
          ),
          if (samagri.isNotEmpty) ...[
            const SizedBox(height: 10),
            Wrap(
              spacing: 6,
              runSpacing: 4,
              children: samagri.map((item) {
                return Container(
                  padding: const EdgeInsets.symmetric(
                    horizontal: 8,
                    vertical: 3,
                  ),
                  decoration: BoxDecoration(
                    color: const Color(0xFFFFF8EE),
                    borderRadius: BorderRadius.circular(8),
                    border: Border.all(
                      color: const Color(0xFFE8D5A3),
                    ),
                  ),
                  child: Text(
                    item,
                    style: GoogleFonts.lato(
                      fontSize: 10,
                      color: const Color(0xFF8A7060),
                    ),
                  ),
                );
              }).toList(),
            ),
          ],
        ],
      ),
    );
  }
}
